project_id = "cgqpfsojhmqytjnvzzqe"

[functions.generate-image]
verify_jwt = true

[functions.tezu-chat]
verify_jwt = true

[functions.tezu-creative]
verify_jwt = true

[functions.zentara-chat]
verify_jwt = true

[functions.zentara-creative]
verify_jwt = true
